### ISSUE TITLE
OS X build fails on Travis

### ISSUE THREAD

**Issue by fredrik-johansson** [fredrik-johansson/arb#168]
There are some new build related problems on Travis:

https://travis-ci.org/fredrik-johansson/arb/jobs/166118340
https://travis-ci.org/fredrik-johansson/arb/jobs/166118341

I don't know the cause.

**Comment by isuruf** [comment]
First problem is because gcc48 is not preinstalled in the travis-ci's new osx image. `brew install gcc48` should fix it. I don't know the reason for the 2nd.

**Comment by isuruf** [comment]
Second issue seems to be because travis-ci changed the default osx image to OS X 10.11 and LD_LIBRARY_PATH is disabled in new OS X versions. Tests cannot find libarb because of it.

**Comment by fredrik-johansson** [comment]
There seems to be a new problem.

**Comment by isuruf** [comment]
This is the second problem I've described earlier. Travis has deprecated one of the images used and has bumped arb to a new osx 10.11 build. 

Two temporary solutions are to
1. Change travis-ci image to osx 10.10
2. Install arb in the same folder as the dependencies and do `make check` after doing a `make install`.

Long term solution would be to fix the Makefile so that OS X 10.11 users can do a `make check` before a `make install`

**Comment by isuruf** [comment]
@fredrik-johansson, I can implement either 1 or 2 and send a PR. Let me know what you think is best for the time being.

**Comment by fredrik-johansson** [comment]
I'm happy either way. Please do whatever you think will require the least amount of work (now and/or in terms of future maintenance).

**Comment by fredrik-johansson** [comment]
This problem is persistent. It would be great if someone could figure out a more reliable workaround...
