### ISSUE TITLE
Spurious Travis build failures on OS X again

### ISSUE THREAD

**Issue by fredrik-johansson** [fredrik-johansson/arb#193]
#https://travis-ci.org/fredrik-johansson/arb/jobs/285748607

The build seems to fail while installing dependencies.

**Comment by isuruf** [comment]
Homebrew failed on travis-ci. https://github.com/travis-ci/travis-ci/issues/8552

**Comment by fredrik-johansson** [comment]
Fixed earlier, but now it's back.

**Comment by isuruf** [comment]
https://github.com/travis-ci/travis-ci/issues/8826

**Comment by fredrik-johansson** [comment]
Still broken...

**Comment by bennybp** [comment]
New to the issue, but it looks like GCC 4.8 was removed from homebrew (https://github.com/Homebrew/homebrew-core/commit/3c5883d02e8869fb986539454b836b4d09d1270d)

From the output of the latest failure:

    homebrew/core/gcc@4.8 was deleted from homebrew/core in commit 3c5883d02:
      gcc@4.8: remove
    
    To show the formula before removal run:
      git -C "$(brew --repo homebrew/core)" show 3c5883d02^:Formula/gcc@4.8.rb
    
    If you still use this formula consider creating your own tap:
      https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html

Interesting that travis doesn't catch that `brew install` failed. I'm guessing it's because multiple commands are batched in .travis.yaml.

**Comment by isuruf** [comment]
Fxied in https://github.com/fredrik-johansson/arb/pull/207
