### ISSUE TITLE
Implement the Hansen & Smith determinant algorithm

### ISSUE THREAD

**Issue by arbguest** [fredrik-johansson/arb#223]
From section 6 of Interval Arithmetic In Matrix Computations Part II, Hansen and Smith 1967:

"Let L be a lower triangular matrix such that L*A_c = U, where A_c is the center of A^I and U is upper triangular. We assume for simplicity that the rows of A were initially permuted so that L can be obtained by numerically stable Gaussian elimination without interchanges. Of course the matrix L contains roundoff errors.

Using this approximate L, compute B^I = L*A^I using interval arithmetic. In general, elements below the diagonal of B^I will be small.

Next perform Gaussian elimination of B^I using interval arithmetic and obtaining an upper triangular matrix T^I. We assume it is not necessary in this step to divide by an interval containing zero.

Finally, we compute [the interval determinant as the product of the diagonal entries of T^I]."

**Comment by fredrik-johansson** [comment]
I actually tested this  already but didn't see an improvement over interval Gaussian elimination. However, some form of preconditioning should still work. Rump (in the Acta Numerica paper) gives a short algorithm based on left and right multiplication by approximate inverses of the approximate LU factors. Actually that algorithm doesn't look correct to me, but it should be possible to fix (perhaps I'm just misunderstanding it).

**Comment by fredrik-johansson** [comment]
Nevermind, I think I see how Rump's algorithm works now. I was just confused because the last step is not included in the Matlab code.

**Comment by fredrik-johansson** [comment]
Done for real matrices.

Actually there is an error in Rump's Acta Numerica paper: taking the product of Gershgorin circles is not known to give a valid enclosure for the determinant in general since the correspondence to eigenvalues is not one-to-one unless the circles are disjoint. I contacted him about this and it turns out that he recently became aware of this problem and has worked out a proof that it does work in the real case, but the complex case is still open.

It's easy to fix the problem by taking the union of the circles and raising to the nth power. This is what I've done in the arb_mat version for now, and it's improvable.

**Comment by fredrik-johansson** [comment]
Done for complex matrices also.
