### ISSUE TITLE
flint.h or flint/flint.h?

### ISSUE THREAD

**Issue by bluescarni** [fredrik-johansson/arb#24]
Currently, some files in Arb (e.g., ``fmpr.h``) include the FLINT headers as ``#include "flint.h"``. I am wondering if this should be ``#include "flint/flint.h"`` instead, as it seems that FLINT headers are commonly installed in a ``flint/`` subdirectory (e.g., ``/usr/include/flint/flint.h`` on my setup).

The current way of including ``flint.h`` essentially prevents to compile files including the Arb headers without adding extra ``-I`` switches to the compiler command line. Or am I missing something?

**Comment by certik** [comment]
@fredrik-johansson any update on this one?

**Comment by Therickaman** [comment]
I just installed flint on my machine (arb standalone).  The relevent output of the installation is:

 mkdir -p /usr/local/lib
mkdir -p /usr/local/include/flint
cp  ulong_extras.h  long_extras.h  perm.h  fmpz.h  fmpz_vec.h  fmpz_poly.h  fmpq_poly.h  fmpz_mat.h  mpfr_vec.h  mpfr_mat.h  nmod_vec.h  nmod_poly.h  nmod_poly_factor.h  arith.h  mpn_extras.h  nmod_mat.h  fmpq.h  fmpq_mat.h  padic.h  fmpz_poly_q.h  fmpz_poly_mat.h  nmod_poly_mat.h  fmpz_mod_poly.h  fmpz_mod_poly_factor.h  fmpz_factor.h  fmpz_poly_factor.h  fft.h  qsieve.h  double_extras.h  padic_poly.h  padic_mat.h  qadic.h  fq.h  fq_vec.h  fq_mat.h  fq_poly.h  fq_poly_factor.h  fq_nmod.h  fq_nmod_vec.h  fq_nmod_mat.h  fq_nmod_poly.h  fq_nmod_poly_factor.h  fq_zech.h  fq_zech_vec.h  fq_zech_mat.h  fq_zech_poly.h  fq_zech_poly_factor.h NTL-interface.h flint.h longlong.h config.h gmpcompat.h fft_tuning.h fmpz-conversions.h profiler.h templates.h  fq_vec_templates.h  fq_mat_templates.h  fq_poly_templates.h  fq_poly_factor_templates.h /usr/local/include/flint
mkdir -p /usr/local/share/flint
cp qadic/CPimport.txt /usr/local/share/flint
mkdir -p /usr/local/include/flint/flintxx
cp flintxx/*.h /usr/local/include/flint/flintxx
cp *xx.h /usr/local/include/flint

Judging by this and looking at the configure file, it seems as though the code causing this issue is lines 248-250.  Those lines are:

if [ -d "${FLINT_INC_DIR}/flint" ]; then
FLINT_INC_DIR="${FLINT_INC_DIR}/flint"
fi

By default, FLINT_INC_DIR="/usr/local".  Also, during the installation, there was no directory created named "/usr/local/flint".  Hence, the condition in lines 248-250 is always false.  I think to desire the functionality that certik desires, the code should read:

if [ -d "${FLINT_INC_DIR}/include/flint" ]; then
FLINT_INC_DIR="${FLINT_INC_DIR}/include/flint"
fi

As far as breaking the installation of flint when flint installs arb as an extention, I'm not quite sure.  I don't think it breaks anything.  When flint installs arb as a standalone package, doesn't flint simply place the arb header files in "/usr/local/include" which is one level higher than where the headers for flint is?

**Comment by rickyefarr** [comment]
Okay, I think I have a work around.  If you agree @fredrik-johansson that it would work and be a suitable "hack", then I'll be happy to implement the idea.  

At the end of the configure file, build a new header like so:
echo "#ifndef ARB_DEPENDS_H__" > arb_depends.h
echo "#define ARB_DEPENDS_H__" >> arb_depends.h
echo "" >> arb_depends.h
echo "#include \"$GMP_INC_DIR/gmp.h\""
echo "#include \"$FLINT_INC_DIR/flint.h\""
/* Do same for all other headers that are needed to build arb */
echo "#endif" >> arb_depends.h

Then, each .h file within the package would include arb_depends.h and never need to include flint.h, gmp.h, and all others.

What do you think?

**Comment by SnarkBoojum** [comment]
If I understand well what I have read on the flint-devel and sage-devel mailing-lists, FLINT and ARB will get more integrated -- in which case one can wonder if moving ARB within FLINT wouldn't be more sensible and solve every problem at once.

**Comment by rickyefarr** [comment]
If FLINT and ARB is to become more integrated in sage, I think that is a great idea.

Just to throw my two cents in, I think it would be nice for arf.h to be independent of arb.h, and arb.h to be independent of acb.h...etc.  So in other words, arf type would be the base type for all other types, i.e. acb.h depends on arb.h which depends on arf.h.  In other words, arf would be same as arb but without using ball arithmetic, arfc type could be created to mirror acb types without ball arithmetic.

Correct me if I'm wrong @fredrik-johansson but I'm assuming most of the functions implemented make a calculation using the midpoint of the interval, and the  error bounds are derived independently?  If so, I don't think it would be very hard to separate.

**Comment by fredrik-johansson** [comment]
Error bounds are mostly derived independently, but it's quite likely that this will change, as performance can be improved by taking the error bounds into account when doing midpoint operations.

On the other hand, at least for basic arithmetic operations, there could still be separate functions that guarantee doing midpoint and radius operations independently.

I might add a complex arf type at some point, but it's not going to compete with MPFR... it's too much work to ensure correct rounding in all edge cases. This is difficult even for arithmetic operations on complex numbers.

It's mainly interesting because to have because it can be used internally for things like polynomial root-finding and linear algebra, where you first compute an approximate numerical solution and then do a rigorous verification step to determine error bounds.

As to FLINT/ARB becoming integrated, I'm not so sure... FLINT has very infrequent releases, and I don't want to be blocked by that.

**Comment by SnarkBoojum** [comment]
FLINT has very infrequent releases, but that's also because it doesn't move fast... if the ARB part of it changes fast... then it might merit supplementary releases. That's something to discuss with William.

**Comment by jdemeyer** [comment]
> The problem isn't installing flint once: it's that I develop flint concurrently, so I always want to work directly against the flint git repository. However, I'm well aware that I'm the only user doing this, which is why I'd be fine with a configure hack, say --local-flint-headers to include flint.h, with flint/flint.h included by default. There are very few instances of flint header files being included in arb header files, so I think the increase in complexity would be negligible.

How about you simply do
```
ln -s . flint
```
such that `flint/flint.h` is the same as `flint.h`?

Then you can safely apply #55.

**Comment by rickyefarr** [comment]
> How about you simply do

> ln -s . flint
> such that flint/flint.h is the same as flint.h?

Would this work for windows as well?  I guess it would work for Fredrik, since I believe he uses linux.  

Perhaps I'm wrong, but I *think* flint headers are set up the way they are because of Windows.  Is that true?

**Comment by argriffing** [comment]
I'm not a packaging expert but I think I agree with everyone saying to use `flint/flint.h`. Similarly, when I did not specify an explicit `--prefix` for arb, arb's `make install` spammed its headers directly into my `/usr/local/include/`. I'm pretty sure that's bad form. Also I think an installed arb conflicts somehow with `make check`.

**Comment by fredrik-johansson** [comment]
Wouldn't installing arb's headers into include/flint/ solve both problems?

**Comment by certik** [comment]
That might work, but in my opinion it is the cleanest is to install Arb header files into `include/arb` and Flint files into `include/flint`.

**Comment by argriffing** [comment]
> Wouldn't installing arb's headers into include/flint/ solve both problems?

That seems weird. What if I'm installing `arb` to a different location than `flint` (for example `/usr/` vs. `/usr/local/`)? What if I don't even have permission to write into the flint directory? Is having dependent projects install their header files into the directory of their dependency even a thing?

**Comment by jdemeyer** [comment]
> Wouldn't installing arb's headers into include/flint/ solve both problems?

I don't think so. It's not because a file in `local/include/flint/foo.h` has `#include "bar.h"` that the preprocessor will look for `local/include/flint/bar.h`

**Comment by jdemeyer** [comment]
> That might work, but in my opinion it is the cleanest to install Arb header files into include/arb and Flint files into include/flint.

+1

**Comment by fredrik-johansson** [comment]
Jeroen: it should work since that's what flint's internal includes already do. The (small) advantage of this solution is that it's compatible with the existing mechanism of installing arb as an extension of flint.

**Comment by fredrik-johansson** [comment]
So I discussed this with Bill and he agreed that it would be fine to drop support for arb as a flint extension module (he's not using that feature anymore). However, we should keep the ability to easily build arb against an uninstalled flint.

**Comment by jdemeyer** [comment]
> Jeroen: it should work since that's what flint's internal includes already do.

You're right: relative include paths do work like that.

**Comment by argriffing** [comment]
Some comments in this thread mention packaging for Linux distros. I'm looking forward to that!

**Comment by SnarkBoojum** [comment]
I've already debian packages for ARB 2.7.0 available here: http://mentors.debian.net/package/arb

I'm mostly waiting to see how the dust settles on the issue of header files before I propose them officially.

**Comment by argriffing** [comment]
>  http://mentors.debian.net/package/arb

I noticed that there's already a debian package called [arb](https://packages.debian.org/sid/arb). Does this mean Fredrik's arb would have to be proposed to Debian under a different name? Or if the existing arb is unmaintained non-free research software then maybe it could be dropped? I don't know much about Debian's processes except that they are very formalized.

For what it's worth, I've written a small domain-specific research code that depends on arb and uses autotools for build/install, and the arb/flint header issue has caused some complications. This issue causes `make dist; make distcheck` to fail, but if I were more clever at writing autoconf scripts then I suppose I could fix this on my end by digging through the user's file system by default at configuration time. My current approach is to require the user to pass the flint header directory to `configure` via CPPFLAGS.

**Comment by SnarkBoojum** [comment]
Hi,

Le lundi 18 janv. 2016 à 10:48:37 (-0800), argriffing a écrit :
> >  http://mentors.debian.net/package/arb
> 
> I noticed that there's already a debian package called 
> [arb](https://packages.debian.org/sid/arb). Does this mean Fredrik's 
> arb would have to be proposed to Debian under a different name? Or if 
> the existing arb is unmaintained non-free research software then maybe 
> it could be dropped? I don't know much about Debian's processes except 
> that they are very formalized.

Yes, I proposed a 2.8.1 package just today, with the source package 
named flint-arb, and the binary packages named libflint-arb1 and 
libflint-arb-dev, to avoid the confusion.

That means code written to compile against arb will have to be patched 
on Debian, but I don't think it's reasonable to expect better : after 
all, collisions of three-letters acronyms are just normal...

Snark on #debian-science

**Comment by fredrik-johansson** [comment]
To reiterate, there seem to be two viable solutions for the header path issue:

1. Change the arb source code to include `flint/flint.h` instead of `flint.h`

2. Change the arb install script to install `flint/arb.h` instead of `arb.h`

Preferences?

**Comment by SnarkBoojum** [comment]
I'd prefer the arb headers in /usr/include/flint/ instead of directly in /usr/include, since some of them are just three-letter names...

**Comment by certik** [comment]
I think you should do:

3) include flint/flint.h and install all arb header filed into arb/

Since Arb is a separate package from Flint, it makes no sense to install
into flint/

**Comment by rwst** [comment]
This now affects compilation of symengine.py with https://github.com/symengine/symengine/pull/787 installed, as well.

**Comment by rwst** [comment]
See also https://github.com/wbhart/flint2/issues/217

**Comment by argriffing** [comment]
> Preferences?

I think @certik's option (3) makes sense.

**Comment by rickyefarr** [comment]
Just so everyone knows (please let me know if you've already planned to do
this), I'm planning on packaging Arb for the Gentoo and funtoo linux
distribution.  Also, eventually I'll do the same for Arch linux.  If you'd
prefer me not to do this Fredrik, please let me know.

Figured I'd let you all know since there were discussion of deb packages.

Thanks,

Rick



On Mon, Feb 1, 2016 at 12:12 PM, argriffing <notifications@github.com>
wrote:

> Preferences?
>
> I think @certik <https://github.com/certik>'s option (3) makes sense.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fredrik-johansson/arb/issues/24#issuecomment-178073734>
> .
>



-- 
Ricky Eugene Farr
University of North Carolina at Greensboro
Mathematics Department

**Comment by fredrik-johansson** [comment]
I've switched from ``flint.h`` to ``flint/flint.h`` in the git master, with a configure hack to create a symbolic link which still allows working against an uninstalled flint. Please test.

BTW, if someone wants to install headers to ``include/arb/arb.h`` instead of ``include/arb.h``, I'll accept a patch that allows doing so *optionally* for now.

**Comment by argriffing** [comment]
> Please test.

Works for me. I've reconfigured/rebuilt/reinstalled arb and rebuilt and tested a project that depends on arb. Everything seems to work and no longer requires the extra `-I` flags. The arb configuration output is
```
$ ./configure
FLINT_LIB_DIR set to /usr/local/lib
FLINT_INC_DIR set to /usr/local/include
Configuring...x86_64-Linux
Testing __builtin_popcountl...yes
Testing native popcount...yes
Testing __thread...yes
ARB was successfully configured.
```

**Comment by fredrik-johansson** [comment]
Closing this absent violent protests.

**Comment by certik** [comment]
I didn't test it, but thanks for fixing it @fredrik-johansson!
