### ISSUE TITLE
Serialization Support

### ISSUE THREAD

**Issue by saraedum** [fredrik-johansson/arb#283]
If I understand the documentation correctly, there is currently no immediate way to write an arb_t/arf_t to a string and then parse that string without loss of precision. (In particular, the [Input and output](http://arblib.org/arf.html#input-and-output) section of the documentation does not contain any input methods.)

Should I make an attempt to add something like that?

**Comment by fredrik-johansson** [comment]
Go ahead. This is a frequently requested feature.

I would make the format for an arf_t two integers `man exp` separated by spaces, with special values for 0/+inf/-inf/nan (e.g. `0 0`, `0 -1`, `0 -2`, `0 -3`). For an arb_t, make that four integers `mid_man mid_exp rad_man rad_exp`. I would use hex instead of decimal for efficiency.

You can use `arf_set_fmpz_2exp` and `arf_get_fmpz_2exp` to implement the conversions. You can serialize a mag_t by converting it to an arf_t first, but for deserializing the radius mantissa, it is best to use `mag_set_ui`, because `arf_get_mag` is inexact. It is a good idea to put in an assertion that the radius mantissa is < 2^MAG_BITS when reading it.

**Comment by saraedum** [comment]
Any suggestions on the naming of the functions? Should they write to a FILE or create a char*?

**Comment by saraedum** [comment]
So, I'll just go ahead then and make this `arb_get_str`, `arb_set_str` and so on. I'll add a flag to `arb_get_str` say `ARB_BINARY` that produces the new format. `arb_get_str` can detect that the format is binary by checking that it does not contain `+/-` but whitespace. @fredrik-johansson

**Comment by fredrik-johansson** [comment]
Hmm, that sounds unsafe to me; I think you want `arb_set_str` to recognize unexpected whitespace as badly formated input. I would rather add some special decoration character to the syntax in that case. 

I was thinking of having something like `arb_dump_str` / `arb_load_str` and `arb_dump_file` / `arb_load_file`.

The advantage of adding a flag to `arb_get_str` as you suggested is that it avoids creating a bunch of separate new functions, especially to support this for more types. The disadvantage is that you have to think more to use the interfaces. There is also no counterpart of `arb_printn` to read from a file right now.

A rather natural alternative would be to allow IEEE 754 hex literals like `0x1fcp-23`, with an `ARB_STR_HEX` flag, and automatic detection in `arb_set_str`. This requires more code for parsing, and external tools also need more code for parsing.

**Comment by saraedum** [comment]
I am fine with `arb_dump_str` / `arb_load_str` and `arb_dump_file` / `arb_load_file`.

**Comment by isuruf** [comment]
You might also want to look at `mpz_export` and `mpz_import` https://gmplib.org/manual/Integer-Import-and-Export.html when designing an API
