### ISSUE TITLE
Makefile problems on OS X 10.10

### ISSUE THREAD

**Issue by mseri** [fredrik-johansson/arb#39]
I've tried to compile Arb (standalone) on OS X 10.10.2,
compiler Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn) or gcc-4.9.
 
Everything seems fine until the compilation ends and this line of the makefile is executed: https://github.com/fredrik-johansson/arb/blob/master/Makefile.in#L111

The problem seems to be that $(OBJS) is empty, and in fact if you remove the line
(e.g `sed -i.breworig 's/$(QUIET_AR) $(AR) rcs libarb.a $(OBJS);//' Makefile`)
everything goes through. 

As expectable `make check` fails:
```
test/t-epsilon_arg.c: In function 'acb_modular_epsilon_arg_naive':
test/t-epsilon_arg.c:52:9: warning: implicit declaration of function 'fmpq_dedekind_sum' [-Wimplicit-function-declaration]
         fmpq_dedekind_sum(t, d, c);
         ^
Undefined symbols for architecture x86_64:
  "_fmpq_dedekind_sum", referenced from:
      _main in ccR5NFtc.o
ld: symbol(s) not found for architecture x86_64
```

Any idea how to fix it?

**Comment by fredrik-johansson** [comment]
Thanks for the feedback. You are not the first person to report issues on OS X. So far I've just suggested using the dynamic build only (`--disable-static`), but it would be great if this fix works!

The `make check` failure is due to accidentally using a function not available in the current release version of flint. You can install the git trunk of flint, or patch the test as I recently did in this commit: https://github.com/fredrik-johansson/arb/commit/b444140a712dc0f701b5cfaa00725b6b5ad7480d

**Comment by mseri** [comment]
Thanks. That's a great news then.

I'm rerunning the checks after patching. If it pass successfully I'll pull a brew formula (that takes care to run the sed line above and install the library).

**Comment by mseri** [comment]
I can confirm that the tests are passing.

**Comment by fredrik-johansson** [comment]
Fix for the build issue in https://github.com/fredrik-johansson/arb/commit/fdd858b1c16dc961106604e19eef259272749e5c

**Comment by fredrik-johansson** [comment]
Absent evidence that things are still broken, closing this issue.
