### ISSUE TITLE
Output radius smaller than radius of input

### ISSUE THREAD

**Issue by rickyefarr** [fredrik-johansson/arb#46]
Consider the following code snippet:

----
#include "acb.h"

void main()
{
	acb_t s,z;
	acb_init(s);
	acb_init(z);

    arb_const_pi(acb_realref(s), 1000);
	arb_const_pi(acb_imagref(s), 1000);

	acb_zeta(z,s,1000);
	acb_printd(z,20);
	printf("\n");

	acb_clear(s);
	acb_clear(z);	
}

---
 The output above will give:
(0.9096902551448360325 - 0.065857401879019999596j)  +/-  (9.94e-302, 9.82e-302j)

Shouldn't the radius of output always be larger (or equal to) the radius of the approximate machine precision midpoint?  

Setting the value of z to be 3+5*i, will result in
 (0.91252658899897131011 + 0.050842871074571362072j)  +/-  (7.88e-305, 1.81e-305j)
which is more drastic.

Maybe I'm wrong, but it appears as though the exponent is moving in the opposite direction.

**Comment by rickyefarr** [comment]
On second thought, this could be because the midpoint is the center of a circle.

**Comment by fredrik-johansson** [comment]
I don't understand the problem.

**Comment by rickyefarr** [comment]
I think maybe I'm not understanding the magnitudes in the result.  Consider the following example, although extreme:

    acb_set_d_d(s, .0000000000000003, 0.0); /*  3*10e-16  */
    acb_printd(s,16);  /* Prints exactly what I would expect (3e-16 + 0j)  +/-  (0, 0j) */
    printf("\n");
    acb_zeta(z,s,53); /* Precision 53 is 15 decimal digits correct */
    acb_printd(z,16); /* (-0.5000000000000002 + 0j)  +/-  (5.03e-17, 0j) */
    printf("\n");

When I use precision 53, I would think the answer would have at most 15 correct digits.  How should (-0.5000000000000002 + 0j)  +/-  (5.03e-17, 0j) be interpreted?  Does this mean that the last digit of two is trustworthy?  I thought the magnitude would have been on the order of 10^-16, so that I know automatically the digit two is questionable.

**Comment by fredrik-johansson** [comment]
It's safest to use arb_printn instead of arb_printd (arb_printn gives you the error bound for the printed decimal value, not just decimal approximations of the midpoint and radius separately).

Some functions use a slightly higher precision internally and don't round the result when they return. The output of acb_zeta(z,s,53) is actually a 58-bit floating-point number here. The midpoint is 144115188075855943 * 2^-58 which differs from the exact value of zeta(s) by about 2.935e-17, and this is less than the computed bound 5.03e-17 so everything is ok.

**Comment by rickyefarr** [comment]
This makes sense.  I didn't realize this.  I'll start using arb_printn instead also.
