### ISSUE TITLE
Add memory manager for arb types

### ISSUE THREAD

**Issue by rickyefarr** [fredrik-johansson/arb#85]
This is a proposal and I'd like to get feedback about this idea.  I've noticed that for operations that are repeated removing local variable initialization and clearing, can lead to quite a speed gain.  On the other hand, doing this is quite impractical because it leads to unreadable code and very hard to track errors.

I **_think_** that a possible solution would be to create a stack for each arb type.  Whenever a variable is initialized, if the stack is empty then initialize as normal (perhaps even add a few more initialized variables to the stack).  If not, pop a variable off the stack to be used for the variable.  Eventually, the stack would be large enough to guarantee local variables are not re-initialized. Especially for polynomial types, this would avoid many calls to the system functions, malloc and free...which causes the kernel to become involved (if I'm not mistaken).

Even if the speed gain is negligible for some types, another added benefit to doing this is the fact that custom data structures would need to be created for each type (stack, queue, linked list, etc.).  Having these structures available to the user could really help with implementing more complex functions.  Also, having these structures customized for each type avoids unnecessary casts to and from a void pointer type.

As another example, the built in function for derivatives of zeta can re-use already completed computations such as log(n+a), for a fixed and n an non-negative integer.

I just wanted to get feedback to see what everyone thought about this idea.  Perhaps I'm incorrect about speed gains.

**Comment by fredrik-johansson** [comment]
There is sort of a memory manager implemented already: in arf/memory_manager.c, #define ARF_USE_CACHE 1

This will reduce the number of malloc and free calls. It's disabled by default, because I couldn't see any improvement on benchmarks when enabling it.

Caching whole arb_t variables could get rid of some overhead. The problem with this is that variables are always initialized to zero, which forces a deallocation anyway.

I don't understand your example with log(n+a). Caching already completed computations seems to be a separate issue.

**Comment by rickyefarr** [comment]
Well, you're right, it really is a separate issue.  I think though that having the data structures I describe would make it easier to handle caching of already completed computations, such as log(n+a), as an extra benefit.
